-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 12:11:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pizzaria_legal` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria_legal` ;

-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `doce` TINYINT NOT NULL,
  `salgada` TINYINT NOT NULL,
  `beirute` TINYINT NOT NULL,
  `tb_categoriacol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza` (
  `id_pizza` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `valor` DECIMAL(4,2) NOT NULL,
  `ingredientes` VARCHAR(80) NOT NULL,
  `borda_recheada` TINYINT NOT NULL,
  `tamanho` CHAR(1) NOT NULL,
  `fk_pizza_cateogoria` INT NOT NULL,
  PRIMARY KEY (`id_pizza`, `fk_pizza_cateogoria`),
  UNIQUE INDEX `id_pizza_UNIQUE` (`id_pizza` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `ingredientes_UNIQUE` (`ingredientes` ASC) VISIBLE,
  INDEX `fk_tb_pizza_tb_categoria_idx` (`fk_pizza_cateogoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pizza_tb_categoria`
    FOREIGN KEY (`fk_pizza_cateogoria`)
    REFERENCES `db_pizzaria_legal`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SELECT * FROM db_pizzaria_legal.tb_categoria;

INSERT INTO tb_categoria (salgada, doce, beirute) VALUES (true, false, false), (false, true, false), (false, false, true);

SELECT * FROM db_pizzaria_legal.tb_pizza;

INSERT INTO tb_pizza (nome, valor, ingredientes, borda_recheada, tamanho, fk_categoria) VALUES ("Bauru", 32.00, "Presunto, mussarela, tomate e azeitonas", false, "G", 1),
("Espanha", 32.00, "Calabresa, lombo, bacon, mussarela e catupiry", true, "G", 1),
("Choconana", 30.99, "Banana fatiada e chocolate", true, "G", 2),
("Americano", 26.9, "Pão Sírio, Presunto, Ovo, Queijo, Alface, Tomate", false, "G", 3);

SELECT * FROM tb_pizza WHERE valor > 45.00;
SELECT * FROM tb_pizza WHERE valor BETWEEN 29 AND 60;
SELECT * FROM tb_pizza WHERE nome LIKE "%C%";

SELECT * FROM tb_categoria INNER JOIN tb_pizza on tb_categoria.idTb_categoria = tb_pizza.fk_categoria; 

SELECT * FROM tb_categoria INNER JOIN tb_pizza on tb_categoria.idTb_categoria = tb_pizza.fk_categoria WHERE tb_pizza.fk_categoria = 1; 

